### PR TITLE
Add Support for Rails 7.1

### PR DESCRIPTION
**Pull request by teresabocchini**
This gem is out of date and causing some rails 7.1 test failures. This just merges in some changes that have been made on the `Studiosity/carmen-rails` [repo](https://github.com/Studiosity/carmen-rails) in order for our fork to support rails 7.1

### CODE REVIEW

**Review by jonhoman — APPROVED** [review]
Can we migrate back to the main line gem?

**Comment by teresabocchini** [comment]
> Can we migrate back to the main line gem?

@jonhoman the main `carmen-rails` gem is no longer maintained, but we can use the `Studiosity/carmen-rails` version that seems to be maintained. keeps us from having to maintain our own fork.

**Comment by jonhoman** [comment]
@teresabocchini I'd probably prefer to update usages of `carmen-rails` to the Studiosity fork rather than continuing to maintain our fork. Any idea if it's feasible to try that for the Rails 7 upgrade?

In general, we should try to avoid maintain forked gems, IMO.

**Comment by teresabocchini** [comment]
@jonhoman yep, it's feasible! I tested it out before replying to make sure it was even doable. I will close this then.

**Pull request closed without merging**
